name: Deploy Documentation

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install sphinx
        pip install ghp-import

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: Deploy documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use your PAT secret here
      run: |
        pip install ghp-import
        ghp-import -n -p -f docs/_build/html -b gh-pages
